apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: api-istio-system
spec:
  # Secret names are always required.
  secretName: api-istio-system
  commonName: api-istio-system.apps.cluster-08df.08df.sandbox1293.opentlc.com
  duration: 721h 
  usages:
    - server auth
  dnsNames:
  - api-istio-system.apps.cluster-08df.08df.sandbox1293.opentlc.com
  issuerRef:
    name: vault-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io 